### ISSUE TITLE
Problems running on Ubuntu 19.10..

### ISSUE THREAD

**Issue by oscarbg** [wintrmvte/VTSCAN#4]
Hi,
I'm on Ubuntu 19.10 and getting this error:
python3 ./vtscan.py ./README.md
I tried applying also https://github.com/TheSecondSun/VTSCAN/pull/1
but error keeps the same..
```
[*] Sent file to VT api
Traceback (most recent call last):
  File "./vtscan.py", line 110, in <module>
    main()
  File "./vtscan.py", line 43, in main
    resource_hash = resp.json()['resource']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/cosmic/.local/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/cosmic/.local/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/cosmic/.local/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by abdelilahxq** [comment]
To solve the problems install the model in this way
`sudo python3 -m pip install -U huepy terminaltables termcolor requests`
